name: Build Docker Image and Trigger METplus Workflow

on:
  push:
    branches:
      - develop
    paths-ignore:
      - 'met/docs/**'

jobs:

  build_met_docker:
    name: Handle Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: .github/jobs/build_docker_image.sh
        env:
          SOURCE_BRANCH: ${GITHUB_REF#"refs/heads/"}
          MET_BASE_IMAGE: minimum

      - name: Push Docker Image
        run: .github/jobs/push_docker_image.sh
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  trigger_metplus:
    name: Trigger METplus testing workflow
    runs-on: ubuntu-latest
    needs: build_met_docker
    steps:
      - name: Print GitHub values for reference
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.METPLUS_BOT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'dtcenter',
              repo: 'METplus',
              workflow_id: 'testing.yml',
              ref: 'develop',
              inputs: {
                repository: '${{ github.repository }}',
                ref: '${{ github.ref }}',
                actor: '${{ github.actor }}',
                sha: '${{ github.sha }}',
                pusher_email: '${{ github.event.pusher.email }}'
              },
            });
